import { getContext, onUnlock } from './audio.js';

// Experimenter voice from pre-recorded files. Quest Browser has no speech
// synthesis at all, so recorded audio is the only voice that works in a headset.
// Files are generated by tools/make-voice.mjs.
const raw = new Map();      // text -> Promise<ArrayBuffer | null>
const decoded = new Map();  // text -> Promise<AudioBuffer | null>
let current = null;

// lines: [{ text, file }]; file is resolved against baseUrl (the room module URL).
export function loadVoice(lines, baseUrl) {
  for (const { text, file } of lines) {
    raw.set(text, fetch(new URL(file, baseUrl))
      .then(r => (r.ok ? r.arrayBuffer() : null))
      .catch(() => null));
  }
}

// Plays the recording for this exact text, stopping the previous one. Asked for before the
// player's first gesture, it waits for it (audio.js, onUnlock). Resolves when the line has
// finished, at once when there is no recording, and unheard (false) on a device with no audio.
export function speak(text) {
  if (!raw.has(text)) return Promise.resolve(false);
  return new Promise((resolve) => onUnlock(() => resolve(play(text))));
}

function play(text) {
  const ctx = getContext();
  if (!ctx) return Promise.resolve(false);
  if (!decoded.has(text)) {
    decoded.set(text, raw.get(text)
      .then(buf => (buf ? ctx.decodeAudioData(buf.slice(0)) : null))
      .catch(() => null));
  }
  return decoded.get(text).then((buffer) => {
    if (!buffer) return false;
    if (current) { try { current.stop(); } catch (e) { /* already stopped */ } }
    const src = ctx.createBufferSource();
    src.buffer = buffer;
    src.connect(ctx.destination);
    current = src;
    // announced for checks that count spoken lines (tools/quest-check.mjs)
    window.dispatchEvent(new CustomEvent('voice-line', { detail: text }));
    return new Promise((resolve) => {
      src.onended = () => resolve(true);
      src.start();
    });
  });
}
